### ISSUE TITLE
Can't install locally. npm install fails 

### ISSUE THREAD

**Issue by vaMuchenje** [whitef0x0/tellform#150]
I tried running `npm install` with both sudo and without.
Getting this ridiculous error log

```
$ sudo npm install
npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /home/tendi/tellform/node_modules/.staging/v8-debug-f389876e
npm WARN prefer global node-inspector@0.12.10 should be installed with -g

> v8-debug@0.7.7 install /home/tendi/tellform/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/tendi/tellform/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^~~~
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/tendi/.node-gyp/7.7.2/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
debug.target.mk:97: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/tendi/tellform/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.1-041001-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/tendi/tellform/node_modules/v8-debug
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tendi/tellform/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.10.1-041001-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/tendi/tellform/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/tendi/tellform/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/tendi/tellform/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
TellForm@2.0.0 /home/tendi/tellform
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.10.1-041001-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tendi/tellform/npm-debug.log

```

**Comment by whitef0x0** [comment]
@vaMuuchenje can you please list:
1. OS and OS version number 
2. Node version 
3. npm version 
4. gcc version

**Comment by whitef0x0** [comment]
Closing due to lack of details.
